// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Connection pooling per query (più veloce)
    url: process.env["DATABASE_URL"],
    // Direct connection per migrazioni (richiesto da Supabase)
    directUrl: process.env["DIRECT_URL"],
  },
});
