// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Per Supabase: usa DIRECT_URL (porta 5432) per evitare PgBouncer
    // PgBouncer (porta 6543) non supporta prepared statements richiesti dalle migrazioni
    url: process.env["DIRECT_URL"],
  },
});
